services:
  - type: web
    name: xuan-quang-stats
    env: python
    buildCommand: pip install -r Back END/requirements.txt
    startCommand: python Back END/app.py
    envVars:
      - key: DATABASE_URL
        value: mssql+pyodbc://sa:viet@Viet/Số liệu thống kê của xã Xuân Quang?driver=ODBC+Driver+17+for+SQL+Server
      - key: FLASK_ENV
        value: production 